### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Jiankai-Sun** [Nmegha2601/activitygraph_transformer#2]
Thank you for your great work!

Some syntax error:
- [out_logits](https://github.com/Nmegha2601/activitygraph_transformer/blob/6f25049f68907d27126e2aa3a7376b4ca780d239/src/models/agt.py#L257) is not defined.
- https://github.com/Nmegha2601/activitygraph_transformer/blob/6f25049f68907d27126e2aa3a7376b4ca780d239/src/models/agt.py#L282
- [target](https://github.com/Nmegha2601/activitygraph_transformer/blob/6f25049f68907d27126e2aa3a7376b4ca780d239/src/models/agt.py#L287) here

**Comment by Nmegha2601** [comment]
Thanks for pointing out
