### ISSUE TITLE
GPU type and OOM

### ISSUE THREAD

**Issue by Jiankai-Sun** [Nmegha2601/activitygraph_transformer#5]
Hi, Thank you for your great work!

In this code, `batch_size` is set to 4. But I encountered Out of Memory error. I couldn't find the hardware configuration for the experiment in the [paper](https://arxiv.org/pdf/2101.08540.pdf) either. How many GPUs do you use to train for batch_size = 4? (I noticed that there is [distributed training](https://github.com/Nmegha2601/activitygraph_transformer/blob/main/src/main.py#L113-L117) such as [SLURM](https://github.com/Nmegha2601/activitygraph_transformer/blob/2a4ba0b96dbd7136b036ab206879cd8f81a4181e/src/utils/misc.py#L364-L370) in the code) What type of GPU and how much memory they have?

Thank you.

**Comment by Hanqer** [comment]
I meet the same question, by changing the batch size to 2 on each GPU, it costs about 15.5G memory. I think a 32G GPU (v100) or 48G GPU (RTX 8000) is needed when using bs=4 or higher.
